language: node_js
node_js:
- '8'
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_fb7a5ab59a36_key -iv $encrypted_fb7a5ab59a36_iv
  -in dong_key.enc -out dong_key -d
- mv dong_key ~/.ssh -f
- chmod 600 ~/.ssh/dong_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/dong_key
- cp .travis/ssh_config ~/.ssh/config
- chmod 600 ~/.ssh/config
install:
- yarn install
script: "-yarn run test"
after_success:
- scp -r -o StrictHostKeyChecking=no ./build dong:/root/

# addons:
# - ssh _known_hosts:"IP"